import os
import json
import datetime
from pathlib import Path
import frontmatter
from config import VAULT_ROOT, BURNOUT_DEEPWORK_THRESHOLD, BURNOUT_CHECK_DAYS

def scan_vault_for_activity(days=7):
    now = datetime.datetime.now()
    cutoff_date = now - datetime.timedelta(days=days)
    
    activity = {}
    for i in range(days):
        d = (now - datetime.timedelta(days=i)).strftime("%Y-%m-%d")
        activity[d] = {"deep": 0, "shallow": 0, "total": 0}
        
    # Walk through vault
    for root, dirs, files in os.walk(VAULT_ROOT):
        if ".obsidian" in root or "00-inbox" in root: # Skip some dirs if needed
            continue
            
        for f in files:
            if f.endswith(".md"):
                file_path = Path(root) / f
                try:
                    with open(file_path, "r", encoding="utf-8") as md_file:
                        post = frontmatter.load(md_file)
                        created = post.get("created")
                        if not created:
                            continue
                            
                        # Handle date formatting
                        if isinstance(created, datetime.date):
                            created_str = created.strftime("%Y-%m-%d")
                        elif isinstance(created, str):
                            created_str = created.split("T")[0]
                        else:
                            continue
                            
                        if created_str in activity:
                            energy = post.get("energy", "shallow").lower()
                            activity[created_str]["total"] += 1
                            if "deep" in energy:
                                activity[created_str]["deep"] += 1
                            else:
                                activity[created_str]["shallow"] += 1
                except Exception as e:
                    # Ignore parsing errors for individual files
                    pass
                    
    return activity

def analyze_burnout(activity):
    sorted_dates = sorted(activity.keys(), reverse=True)
    recent_days = sorted_dates[:BURNOUT_CHECK_DAYS]
    
    consecutive_low_deep_work = 0
    for d in recent_days:
        stats = activity[d]
        if stats["total"] > 0:
            rate = stats["deep"] / stats["total"]
        else:
            rate = 0.0 # No work implies 0% deep work
            
        if rate < BURNOUT_DEEPWORK_THRESHOLD:
            consecutive_low_deep_work += 1
            
    is_burnout_risk = consecutive_low_deep_work >= BURNOUT_CHECK_DAYS
    return is_burnout_risk, recent_days

def create_alert():
    now = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    timestamp = now.strftime("%H%M%S")
    
    alert_content = f"""---
id: ALERT-{date_str}-{timestamp}
title: "⚠️ BURNOUT ALERT"
created: {date_str}
vault: 00-inbox
type: daily
tags: [alert, burnout]
---

# ⚠️ BURNOUT RISK DETECTED

Hệ thống Burnout Radar phát hiện tỷ lệ Deep Work của bạn dưới ngưỡng {BURNOUT_DEEPWORK_THRESHOLD*100}% trong {BURNOUT_CHECK_DAYS} ngày liên tiếp.

**Đề xuất hành động:**
- Giảm 30% khối lượng task Deep Work trong tuần tới.
- Lên lịch nghỉ ngơi hoàn toàn (1 ngày không màn hình).
- Ưu tiên giải quyết các công việc tồn đọng nhẹ nhàng (Shallow Work).

*Generated by burnout_radar.py at {now.strftime("%Y-%m-%d %H:%M:%S")}*
"""
    
    inbox_dir = VAULT_ROOT / "00-inbox"
    inbox_dir.mkdir(parents=True, exist_ok=True)
    alert_path = inbox_dir / f"BURNOUT_ALERT_{date_str}.md"
    
    with open(alert_path, "w", encoding="utf-8") as f:
        f.write(alert_content)
        
    print(f"Created Burnout Alert at {alert_path}")

def run_radar():
    print("Running Burnout Radar...")
    activity = scan_vault_for_activity(7)
    
    for date, stats in sorted(activity.items()):
        total = stats["total"]
        rate = (stats["deep"]/total*100) if total > 0 else 0
        print(f"{date}: Total={total}, Deep={stats['deep']}, Rate={rate:.1f}%")
        
    risk, recent = analyze_burnout(activity)
    
    if risk:
        print(f"WARNING: Burnout risk detected! Deep work < {BURNOUT_DEEPWORK_THRESHOLD*100}% for {BURNOUT_CHECK_DAYS} consecutive days.")
        create_alert()
    else:
        print("Status: Normal. Keep up the good work!")

if __name__ == "__main__":
    run_radar()
